In [30]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [31]:
## Load the dataset
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [32]:
## Preprocess the data
### Drop irrelevant columns
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [33]:
## Encode categorical variables
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [34]:
## Onehot encode 'Geography
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [35]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [36]:
geo_encoded_df=pd.DataFrame(geo_encoder,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [37]:
## Combine one hot encoder columns with the original data
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [38]:
## Save the encoders and sscaler
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [39]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [40]:
## Divide the dataset into independent and dependent features
X=data.drop('Exited',axis=1)
y=data['Exited']

## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [41]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [42]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [43]:
with open('scaler_classification.pkl','wb') as file:
    pickle.dump(scaler,file)

In [15]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

### ANN Implementation

In [16]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

/Users/pranav/Documents/AI projects/Churn Modelling/annclassification/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [17]:
(X_train.shape[1],)

(12,)

In [18]:
## ANN Model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), ## Hidden layer 1 Connected with input layer
    # Dense(32,activation='relu'), ## Hidden layer 2
    Dense(1,activation='sigmoid')  ## output layer
])

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 1)                 65

=================================================================
Total params: 897 (3.50 KB)
Trainable params: 897 (3.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [20]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.0001)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

In [21]:
## compile the model
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

In [22]:
## Set up the Tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [23]:
## Set up Early Stopping
# early_stopping_callback=EarlyStopping(monitor='val_loss',patience=20,restore_best_weights=True)
# early_stopping_callback=EarlyStopping(monitor='val_loss',restore_best_weights=True)

In [25]:
### Train the model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    # callbacks=[tensorflow_callback,early_stopping_callback]
    callbacks=[tensorflow_callback]
)

Epoch 1/100
250/250 [==============================] - 0s 669us/step - loss: 0.6963 - accuracy: 0.5381 - val_loss: 0.6132 - val_accuracy: 0.6805
Epoch 2/100
250/250 [==============================] - 0s 381us/step - loss: 0.5713 - accuracy: 0.7486 - val_loss: 0.5249 - val_accuracy: 0.7980
Epoch 3/100
250/250 [==============================] - 0s 369us/step - loss: 0.5098 - accuracy: 0.7984 - val_loss: 0.4793 - val_accuracy: 0.8060
Epoch 4/100
250/250 [==============================] - 0s 377us/step - loss: 0.4776 - accuracy: 0.8005 - val_loss: 0.4543 - val_accuracy: 0.8090
Epoch 5/100
250/250 [==============================] - 0s 367us/step - loss: 0.4592 - accuracy: 0.8037 - val_loss: 0.4391 - val_accuracy: 0.8135
Epoch 6/100
250/250 [==============================] - 0s 374us/step - loss: 0.4477 - accuracy: 0.8065 - val_loss: 0.4289 - val_accuracy: 0.8170
Epoch 7/100
250/250 [==============================] - 0s 446us/step - loss: 0.4399 - accuracy: 0.8099 - val_loss: 0.4221 - val_accuracy: 0.8190
Epoch 8/100
250/250 [==============================] - 0s 373us/step - loss: 0.4344 - accuracy: 0.8129 - val_loss: 0.4170 - val_accuracy: 0.8180
Epoch 9/100
250/250 [==============================] - 0s 372us/step - loss: 0.4302 - accuracy: 0.8139 - val_loss: 0.4129 - val_accuracy: 0.8190
Epoch 10/100
250/250 [==============================] - 0s 379us/step - loss: 0.4267 - accuracy: 0.8145 - val_loss: 0.4096 - val_accuracy: 0.8210
Epoch 11/100
250/250 [==============================] - 0s 372us/step - loss: 0.4236 - accuracy: 0.8173 - val_loss: 0.4067 - val_accuracy: 0.8225
Epoch 12/100
250/250 [==============================] - 0s 374us/step - loss: 0.4208 - accuracy: 0.8194 - val_loss: 0.4039 - val_accuracy: 0.8245
Epoch 13/100
250/250 [==============================] - 0s 377us/step - loss: 0.4182 - accuracy: 0.8200 - val_loss: 0.4015 - val_accuracy: 0.8260
Epoch 14/100
250/250 [==============================] - 0s 370us/step - loss: 0.4156 - accuracy: 0.8220 - val_loss: 0.3991 - val_accuracy: 0.8295
Epoch 15/100
250/250 [==============================] - 0s 367us/step - loss: 0.4130 - accuracy: 0.8231 - val_loss: 0.3968 - val_accuracy: 0.8295
Epoch 16/100
250/250 [==============================] - 0s 369us/step - loss: 0.4105 - accuracy: 0.8245 - val_loss: 0.3944 - val_accuracy: 0.8300
Epoch 17/100
250/250 [==============================] - 0s 361us/step - loss: 0.4080 - accuracy: 0.8266 - val_loss: 0.3921 - val_accuracy: 0.8310
Epoch 18/100
250/250 [==============================] - 0s 365us/step - loss: 0.4054 - accuracy: 0.8276 - val_loss: 0.3898 - val_accuracy: 0.8315
Epoch 19/100
250/250 [==============================] - 0s 362us/step - loss: 0.4029 - accuracy: 0.8290 - val_loss: 0.3876 - val_accuracy: 0.8325
Epoch 20/100
250/250 [==============================] - 0s 362us/step - loss: 0.4003 - accuracy: 0.8309 - val_loss: 0.3855 - val_accuracy: 0.8335
Epoch 21/100
250/250 [==============================] - 0s 362us/step - loss: 0.3977 - accuracy: 0.8326 - val_loss: 0.3833 - val_accuracy: 0.8330
Epoch 22/100
250/250 [==============================] - 0s 367us/step - loss: 0.3951 - accuracy: 0.8360 - val_loss: 0.3811 - val_accuracy: 0.8345
Epoch 23/100
250/250 [==============================] - 0s 362us/step - loss: 0.3926 - accuracy: 0.8366 - val_loss: 0.3790 - val_accuracy: 0.8350
Epoch 24/100
250/250 [==============================] - 0s 365us/step - loss: 0.3901 - accuracy: 0.8375 - val_loss: 0.3769 - val_accuracy: 0.8365
Epoch 25/100
250/250 [==============================] - 0s 363us/step - loss: 0.3876 - accuracy: 0.8396 - val_loss: 0.3749 - val_accuracy: 0.8370
Epoch 26/100
250/250 [==============================] - 0s 365us/step - loss: 0.3852 - accuracy: 0.8397 - val_loss: 0.3732 - val_accuracy: 0.8370
Epoch 27/100
250/250 [==============================] - 0s 368us/step - loss: 0.3829 - accuracy: 0.8407 - val_loss: 0.3713 - val_accuracy: 0.8385
Epoch 28/100
250/250 [==============================] - 0s 364us/step - loss: 0.3807 - accuracy: 0.8420 - val_loss: 0.3696 - val_accuracy: 0.8390
Epoch 29/100
250/250 [==============================] - 0s 362us/step - loss: 0.3786 - accuracy: 0.8435 - val_loss: 0.3680 - val_accuracy: 0.8410
Epoch 30/100
250/250 [==============================] - 0s 364us/step - loss: 0.3765 - accuracy: 0.8447 - val_loss: 0.3664 - val_accuracy: 0.8415
Epoch 31/100
250/250 [==============================] - 0s 358us/step - loss: 0.3746 - accuracy: 0.8461 - val_loss: 0.3649 - val_accuracy: 0.8435
Epoch 32/100
250/250 [==============================] - 0s 366us/step - loss: 0.3727 - accuracy: 0.8470 - val_loss: 0.3636 - val_accuracy: 0.8445
Epoch 33/100
250/250 [==============================] - 0s 368us/step - loss: 0.3710 - accuracy: 0.8470 - val_loss: 0.3623 - val_accuracy: 0.8465
Epoch 34/100
250/250 [==============================] - 0s 364us/step - loss: 0.3693 - accuracy: 0.8487 - val_loss: 0.3610 - val_accuracy: 0.8475
Epoch 35/100
250/250 [==============================] - 0s 364us/step - loss: 0.3677 - accuracy: 0.8493 - val_loss: 0.3601 - val_accuracy: 0.8480
Epoch 36/100
250/250 [==============================] - 0s 378us/step - loss: 0.3662 - accuracy: 0.8510 - val_loss: 0.3590 - val_accuracy: 0.8495
Epoch 37/100
250/250 [==============================] - 0s 374us/step - loss: 0.3648 - accuracy: 0.8514 - val_loss: 0.3580 - val_accuracy: 0.8515
Epoch 38/100
250/250 [==============================] - 0s 377us/step - loss: 0.3634 - accuracy: 0.8518 - val_loss: 0.3571 - val_accuracy: 0.8525
Epoch 39/100
250/250 [==============================] - 0s 429us/step - loss: 0.3622 - accuracy: 0.8533 - val_loss: 0.3563 - val_accuracy: 0.8550
Epoch 40/100
250/250 [==============================] - 0s 371us/step - loss: 0.3610 - accuracy: 0.8535 - val_loss: 0.3554 - val_accuracy: 0.8540
Epoch 41/100
250/250 [==============================] - 0s 415us/step - loss: 0.3598 - accuracy: 0.8540 - val_loss: 0.3547 - val_accuracy: 0.8545
Epoch 42/100
250/250 [==============================] - 0s 422us/step - loss: 0.3588 - accuracy: 0.8531 - val_loss: 0.3541 - val_accuracy: 0.8545
Epoch 43/100
250/250 [==============================] - 0s 367us/step - loss: 0.3577 - accuracy: 0.8541 - val_loss: 0.3535 - val_accuracy: 0.8535
Epoch 44/100
250/250 [==============================] - 0s 367us/step - loss: 0.3568 - accuracy: 0.8549 - val_loss: 0.3529 - val_accuracy: 0.8540
Epoch 45/100
250/250 [==============================] - 0s 366us/step - loss: 0.3559 - accuracy: 0.8562 - val_loss: 0.3524 - val_accuracy: 0.8535
Epoch 46/100
250/250 [==============================] - 0s 367us/step - loss: 0.3550 - accuracy: 0.8555 - val_loss: 0.3519 - val_accuracy: 0.8545
Epoch 47/100
250/250 [==============================] - 0s 368us/step - loss: 0.3541 - accuracy: 0.8556 - val_loss: 0.3515 - val_accuracy: 0.8560
Epoch 48/100
250/250 [==============================] - 0s 368us/step - loss: 0.3534 - accuracy: 0.8559 - val_loss: 0.3511 - val_accuracy: 0.8555
Epoch 49/100
250/250 [==============================] - 0s 367us/step - loss: 0.3526 - accuracy: 0.8561 - val_loss: 0.3506 - val_accuracy: 0.8550
Epoch 50/100
250/250 [==============================] - 0s 365us/step - loss: 0.3519 - accuracy: 0.8565 - val_loss: 0.3503 - val_accuracy: 0.8550
Epoch 51/100
250/250 [==============================] - 0s 367us/step - loss: 0.3512 - accuracy: 0.8569 - val_loss: 0.3499 - val_accuracy: 0.8540
Epoch 52/100
250/250 [==============================] - 0s 366us/step - loss: 0.3506 - accuracy: 0.8568 - val_loss: 0.3495 - val_accuracy: 0.8530
Epoch 53/100
250/250 [==============================] - 0s 366us/step - loss: 0.3500 - accuracy: 0.8565 - val_loss: 0.3493 - val_accuracy: 0.8530
Epoch 54/100
250/250 [==============================] - 0s 368us/step - loss: 0.3494 - accuracy: 0.8566 - val_loss: 0.3489 - val_accuracy: 0.8545
Epoch 55/100
250/250 [==============================] - 0s 366us/step - loss: 0.3488 - accuracy: 0.8565 - val_loss: 0.3489 - val_accuracy: 0.8535
Epoch 56/100
250/250 [==============================] - 0s 422us/step - loss: 0.3482 - accuracy: 0.8575 - val_loss: 0.3485 - val_accuracy: 0.8540
Epoch 57/100
250/250 [==============================] - 0s 372us/step - loss: 0.3477 - accuracy: 0.8583 - val_loss: 0.3482 - val_accuracy: 0.8535
Epoch 58/100
250/250 [==============================] - 0s 366us/step - loss: 0.3473 - accuracy: 0.8570 - val_loss: 0.3481 - val_accuracy: 0.8540
Epoch 59/100
250/250 [==============================] - 0s 370us/step - loss: 0.3467 - accuracy: 0.8575 - val_loss: 0.3479 - val_accuracy: 0.8540
Epoch 60/100
250/250 [==============================] - 0s 368us/step - loss: 0.3463 - accuracy: 0.8579 - val_loss: 0.3478 - val_accuracy: 0.8540
Epoch 61/100
250/250 [==============================] - 0s 366us/step - loss: 0.3459 - accuracy: 0.8577 - val_loss: 0.3477 - val_accuracy: 0.8550
Epoch 62/100
250/250 [==============================] - 0s 368us/step - loss: 0.3455 - accuracy: 0.8581 - val_loss: 0.3475 - val_accuracy: 0.8540
Epoch 63/100
250/250 [==============================] - 0s 368us/step - loss: 0.3451 - accuracy: 0.8579 - val_loss: 0.3473 - val_accuracy: 0.8545
Epoch 64/100
250/250 [==============================] - 0s 371us/step - loss: 0.3447 - accuracy: 0.8576 - val_loss: 0.3474 - val_accuracy: 0.8560
Epoch 65/100
250/250 [==============================] - 0s 372us/step - loss: 0.3443 - accuracy: 0.8575 - val_loss: 0.3471 - val_accuracy: 0.8550
Epoch 66/100
250/250 [==============================] - 0s 378us/step - loss: 0.3440 - accuracy: 0.8577 - val_loss: 0.3471 - val_accuracy: 0.8545
Epoch 67/100
250/250 [==============================] - 0s 391us/step - loss: 0.3436 - accuracy: 0.8579 - val_loss: 0.3469 - val_accuracy: 0.8545
Epoch 68/100
250/250 [==============================] - 0s 397us/step - loss: 0.3433 - accuracy: 0.8575 - val_loss: 0.3469 - val_accuracy: 0.8550
Epoch 69/100
250/250 [==============================] - 0s 406us/step - loss: 0.3430 - accuracy: 0.8579 - val_loss: 0.3467 - val_accuracy: 0.8550
Epoch 70/100
250/250 [==============================] - 0s 421us/step - loss: 0.3427 - accuracy: 0.8574 - val_loss: 0.3465 - val_accuracy: 0.8555
Epoch 71/100
250/250 [==============================] - 0s 373us/step - loss: 0.3425 - accuracy: 0.8581 - val_loss: 0.3465 - val_accuracy: 0.8555
Epoch 72/100
250/250 [==============================] - 0s 383us/step - loss: 0.3422 - accuracy: 0.8572 - val_loss: 0.3465 - val_accuracy: 0.8555
Epoch 73/100
250/250 [==============================] - 0s 375us/step - loss: 0.3418 - accuracy: 0.8572 - val_loss: 0.3464 - val_accuracy: 0.8555
Epoch 74/100
250/250 [==============================] - 0s 368us/step - loss: 0.3416 - accuracy: 0.8568 - val_loss: 0.3462 - val_accuracy: 0.8570
Epoch 75/100
250/250 [==============================] - 0s 377us/step - loss: 0.3414 - accuracy: 0.8571 - val_loss: 0.3460 - val_accuracy: 0.8570
Epoch 76/100
250/250 [==============================] - 0s 371us/step - loss: 0.3411 - accuracy: 0.8572 - val_loss: 0.3460 - val_accuracy: 0.8560
Epoch 77/100
250/250 [==============================] - 0s 366us/step - loss: 0.3409 - accuracy: 0.8575 - val_loss: 0.3459 - val_accuracy: 0.8565
Epoch 78/100
250/250 [==============================] - 0s 368us/step - loss: 0.3406 - accuracy: 0.8577 - val_loss: 0.3459 - val_accuracy: 0.8580
Epoch 79/100
250/250 [==============================] - 0s 369us/step - loss: 0.3404 - accuracy: 0.8580 - val_loss: 0.3459 - val_accuracy: 0.8575
Epoch 80/100
250/250 [==============================] - 0s 373us/step - loss: 0.3402 - accuracy: 0.8579 - val_loss: 0.3459 - val_accuracy: 0.8585
Epoch 81/100
250/250 [==============================] - 0s 371us/step - loss: 0.3400 - accuracy: 0.8585 - val_loss: 0.3456 - val_accuracy: 0.8580
Epoch 82/100
250/250 [==============================] - 0s 387us/step - loss: 0.3398 - accuracy: 0.8580 - val_loss: 0.3456 - val_accuracy: 0.8575
Epoch 83/100
250/250 [==============================] - 0s 391us/step - loss: 0.3396 - accuracy: 0.8579 - val_loss: 0.3456 - val_accuracy: 0.8570
Epoch 84/100
250/250 [==============================] - 0s 410us/step - loss: 0.3394 - accuracy: 0.8580 - val_loss: 0.3455 - val_accuracy: 0.8575
Epoch 85/100
250/250 [==============================] - 0s 395us/step - loss: 0.3391 - accuracy: 0.8587 - val_loss: 0.3455 - val_accuracy: 0.8575
Epoch 86/100
250/250 [==============================] - 0s 372us/step - loss: 0.3389 - accuracy: 0.8589 - val_loss: 0.3453 - val_accuracy: 0.8580
Epoch 87/100
250/250 [==============================] - 0s 373us/step - loss: 0.3387 - accuracy: 0.8589 - val_loss: 0.3454 - val_accuracy: 0.8585
Epoch 88/100
250/250 [==============================] - 0s 371us/step - loss: 0.3386 - accuracy: 0.8590 - val_loss: 0.3454 - val_accuracy: 0.8585
Epoch 89/100
250/250 [==============================] - 0s 373us/step - loss: 0.3384 - accuracy: 0.8600 - val_loss: 0.3454 - val_accuracy: 0.8585
Epoch 90/100
250/250 [==============================] - 0s 371us/step - loss: 0.3382 - accuracy: 0.8585 - val_loss: 0.3453 - val_accuracy: 0.8585
Epoch 91/100
250/250 [==============================] - 0s 375us/step - loss: 0.3380 - accuracy: 0.8590 - val_loss: 0.3453 - val_accuracy: 0.8590
Epoch 92/100
250/250 [==============================] - 0s 372us/step - loss: 0.3379 - accuracy: 0.8600 - val_loss: 0.3454 - val_accuracy: 0.8600
Epoch 93/100
250/250 [==============================] - 0s 446us/step - loss: 0.3377 - accuracy: 0.8593 - val_loss: 0.3452 - val_accuracy: 0.8590
Epoch 94/100
250/250 [==============================] - 0s 578us/step - loss: 0.3375 - accuracy: 0.8595 - val_loss: 0.3451 - val_accuracy: 0.8600
Epoch 95/100
250/250 [==============================] - 0s 385us/step - loss: 0.3374 - accuracy: 0.8591 - val_loss: 0.3452 - val_accuracy: 0.8600
Epoch 96/100
250/250 [==============================] - 0s 373us/step - loss: 0.3372 - accuracy: 0.8593 - val_loss: 0.3452 - val_accuracy: 0.8595
Epoch 97/100
250/250 [==============================] - 0s 369us/step - loss: 0.3371 - accuracy: 0.8596 - val_loss: 0.3451 - val_accuracy: 0.8595
Epoch 98/100
250/250 [==============================] - 0s 371us/step - loss: 0.3369 - accuracy: 0.8597 - val_loss: 0.3451 - val_accuracy: 0.8595
Epoch 99/100
250/250 [==============================] - 0s 373us/step - loss: 0.3368 - accuracy: 0.8587 - val_loss: 0.3450 - val_accuracy: 0.8590
Epoch 100/100
250/250 [==============================] - 0s 400us/step - loss: 0.3367 - accuracy: 0.8594 - val_loss: 0.3450 - val_accuracy: 0.8590

In [26]:
model.save('churn_classification_model.h5')

/Users/pranav/Documents/AI projects/Churn Modelling/annclassification/venv/lib/python3.9/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [27]:
## Load Tensorboard Extension
%load_ext tensorboard

In [29]:
%tensorboard --logdir logs/fit/20260326-184548

Reusing TensorBoard on port 6006 (pid 49187), started 0:00:02 ago. (Use '!kill 49187' to kill it.)