In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [24]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [25]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [26]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [27]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [28]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [29]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [ ]:
# Split the data into features and target
X = data.drop(['EstimatedSalary', 'Exited'], axis=1)
y = data['EstimatedSalary']

X.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,0,0.0,0.0,1.0

In [31]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [32]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [33]:
# Save the encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler_regression.pkl', 'wb') as file:
    pickle.dump(scaler, file)

#### ANN Regression Problem statement

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

/Users/pranav/Documents/AI projects/Churn Modelling/annclassification/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [13]:
# Build the model
model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(128, activation='relu'),
    Dense(1)  # Output layer for regression
])
opt = tf.keras.optimizers.Adam(learning_rate=0.0001)
## compile the model
model.compile(optimizer=opt,loss='mean_absolute_error',metrics=['mae'])

model.summary()

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 128)               1664

 dense_1 (Dense)             (None, 128)               16512

 dense_2 (Dense)             (None, 1)                 129

=================================================================
Total params: 18305 (71.50 KB)
Trainable params: 18305 (71.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [14]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [15]:
# Set up Early Stopping
# early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [16]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    # callbacks=[early_stopping_callback, tensorboard_callback]
    callbacks=[tensorboard_callback]
)

Epoch 1/100
250/250 [==============================] - 0s 856us/step - loss: 100429.1562 - mae: 100429.1562 - val_loss: 98720.1953 - val_mae: 98720.1953
Epoch 2/100
250/250 [==============================] - 0s 446us/step - loss: 100418.1094 - mae: 100418.1094 - val_loss: 98702.9375 - val_mae: 98702.9375
Epoch 3/100
250/250 [==============================] - 0s 438us/step - loss: 100391.9844 - mae: 100391.9844 - val_loss: 98666.6094 - val_mae: 98666.6094
Epoch 4/100
250/250 [==============================] - 0s 436us/step - loss: 100343.1094 - mae: 100343.1094 - val_loss: 98603.7891 - val_mae: 98603.7891
Epoch 5/100
250/250 [==============================] - 0s 436us/step - loss: 100264.7656 - mae: 100264.7656 - val_loss: 98509.2969 - val_mae: 98509.2969
Epoch 6/100
250/250 [==============================] - 0s 434us/step - loss: 100152.3516 - mae: 100152.3516 - val_loss: 98378.5234 - val_mae: 98378.5234
Epoch 7/100
250/250 [==============================] - 0s 440us/step - loss: 100002.3828 - mae: 100002.3828 - val_loss: 98209.0391 - val_mae: 98209.0391
Epoch 8/100
250/250 [==============================] - 0s 442us/step - loss: 99812.7109 - mae: 99812.7109 - val_loss: 97999.3516 - val_mae: 97999.3516
Epoch 9/100
250/250 [==============================] - 0s 605us/step - loss: 99581.5625 - mae: 99581.5625 - val_loss: 97747.3438 - val_mae: 97747.3438
Epoch 10/100
250/250 [==============================] - 0s 438us/step - loss: 99307.3594 - mae: 99307.3594 - val_loss: 97451.9141 - val_mae: 97451.9141
Epoch 11/100
250/250 [==============================] - 0s 445us/step - loss: 98988.4141 - mae: 98988.4141 - val_loss: 97112.0938 - val_mae: 97112.0938
Epoch 12/100
250/250 [==============================] - 0s 439us/step - loss: 98624.6484 - mae: 98624.6484 - val_loss: 96727.1562 - val_mae: 96727.1562
Epoch 13/100
250/250 [==============================] - 0s 469us/step - loss: 98216.7266 - mae: 98216.7266 - val_loss: 96296.5703 - val_mae: 96296.5703
Epoch 14/100
250/250 [==============================] - 0s 466us/step - loss: 97763.1562 - mae: 97763.1562 - val_loss: 95819.4844 - val_mae: 95819.4844
Epoch 15/100
250/250 [==============================] - 0s 441us/step - loss: 97263.3516 - mae: 97263.3516 - val_loss: 95296.3438 - val_mae: 95296.3438
Epoch 16/100
250/250 [==============================] - 0s 443us/step - loss: 96717.2031 - mae: 96717.2031 - val_loss: 94728.2891 - val_mae: 94728.2891
Epoch 17/100
250/250 [==============================] - 0s 477us/step - loss: 96126.8438 - mae: 96126.8438 - val_loss: 94116.0078 - val_mae: 94116.0078
Epoch 18/100
250/250 [==============================] - 0s 440us/step - loss: 95491.2734 - mae: 95491.2734 - val_loss: 93460.6953 - val_mae: 93460.6953
Epoch 19/100
250/250 [==============================] - 0s 437us/step - loss: 94810.5859 - mae: 94810.5859 - val_loss: 92758.3438 - val_mae: 92758.3438
Epoch 20/100
250/250 [==============================] - 0s 436us/step - loss: 94086.6641 - mae: 94086.6641 - val_loss: 92011.3594 - val_mae: 92011.3594
Epoch 21/100
250/250 [==============================] - 0s 441us/step - loss: 93319.6641 - mae: 93319.6641 - val_loss: 91220.4609 - val_mae: 91220.4609
Epoch 22/100
250/250 [==============================] - 0s 446us/step - loss: 92509.3047 - mae: 92509.3047 - val_loss: 90383.4062 - val_mae: 90383.4062
Epoch 23/100
250/250 [==============================] - 0s 468us/step - loss: 91651.8906 - mae: 91651.8906 - val_loss: 89508.8984 - val_mae: 89508.8984
Epoch 24/100
250/250 [==============================] - 0s 449us/step - loss: 90752.1875 - mae: 90752.1875 - val_loss: 88599.0156 - val_mae: 88599.0156
Epoch 25/100
250/250 [==============================] - 0s 437us/step - loss: 89815.4688 - mae: 89815.4688 - val_loss: 87653.2109 - val_mae: 87653.2109
Epoch 26/100
250/250 [==============================] - 0s 470us/step - loss: 88841.6328 - mae: 88841.6328 - val_loss: 86668.7344 - val_mae: 86668.7344
Epoch 27/100
250/250 [==============================] - 0s 451us/step - loss: 87829.3516 - mae: 87829.3516 - val_loss: 85654.5703 - val_mae: 85654.5703
Epoch 28/100
250/250 [==============================] - 0s 441us/step - loss: 86783.4062 - mae: 86783.4062 - val_loss: 84604.0312 - val_mae: 84604.0312
Epoch 29/100
250/250 [==============================] - 0s 441us/step - loss: 85700.3125 - mae: 85700.3125 - val_loss: 83519.0625 - val_mae: 83519.0625
Epoch 30/100
250/250 [==============================] - 0s 437us/step - loss: 84583.8750 - mae: 84583.8750 - val_loss: 82410.6172 - val_mae: 82410.6172
Epoch 31/100
250/250 [==============================] - 0s 440us/step - loss: 83441.3984 - mae: 83441.3984 - val_loss: 81276.4297 - val_mae: 81276.4297
Epoch 32/100
250/250 [==============================] - 0s 444us/step - loss: 82272.7734 - mae: 82272.7734 - val_loss: 80122.3047 - val_mae: 80122.3047
Epoch 33/100
250/250 [==============================] - 0s 447us/step - loss: 81077.0781 - mae: 81077.0781 - val_loss: 78944.7578 - val_mae: 78944.7578
Epoch 34/100
250/250 [==============================] - 0s 445us/step - loss: 79866.7422 - mae: 79866.7422 - val_loss: 77753.8594 - val_mae: 77753.8594
Epoch 35/100
250/250 [==============================] - 0s 442us/step - loss: 78640.5234 - mae: 78640.5234 - val_loss: 76556.8125 - val_mae: 76556.8125
Epoch 36/100
250/250 [==============================] - 0s 444us/step - loss: 77400.9453 - mae: 77400.9453 - val_loss: 75350.4688 - val_mae: 75350.4688
Epoch 37/100
250/250 [==============================] - 0s 469us/step - loss: 76150.5312 - mae: 76150.5312 - val_loss: 74133.8047 - val_mae: 74133.8047
Epoch 38/100
250/250 [==============================] - 0s 455us/step - loss: 74889.4375 - mae: 74889.4375 - val_loss: 72911.2891 - val_mae: 72911.2891
Epoch 39/100
250/250 [==============================] - 0s 440us/step - loss: 73628.3594 - mae: 73628.3594 - val_loss: 71700.2891 - val_mae: 71700.2891
Epoch 40/100
250/250 [==============================] - 0s 440us/step - loss: 72371.0156 - mae: 72371.0156 - val_loss: 70492.5547 - val_mae: 70492.5547
Epoch 41/100
250/250 [==============================] - 0s 440us/step - loss: 71114.0938 - mae: 71114.0938 - val_loss: 69296.4219 - val_mae: 69296.4219
Epoch 42/100
250/250 [==============================] - 0s 440us/step - loss: 69860.5547 - mae: 69860.5547 - val_loss: 68103.1172 - val_mae: 68103.1172
Epoch 43/100
250/250 [==============================] - 0s 465us/step - loss: 68617.3672 - mae: 68617.3672 - val_loss: 66922.6484 - val_mae: 66922.6484
Epoch 44/100
250/250 [==============================] - 0s 438us/step - loss: 67385.6641 - mae: 67385.6641 - val_loss: 65760.7031 - val_mae: 65760.7031
Epoch 45/100
250/250 [==============================] - 0s 437us/step - loss: 66170.5781 - mae: 66170.5781 - val_loss: 64632.5000 - val_mae: 64632.5000
Epoch 46/100
250/250 [==============================] - 0s 440us/step - loss: 64985.2578 - mae: 64985.2578 - val_loss: 63540.3828 - val_mae: 63540.3828
Epoch 47/100
250/250 [==============================] - 0s 437us/step - loss: 63839.6953 - mae: 63839.6953 - val_loss: 62478.8633 - val_mae: 62478.8633
Epoch 48/100
250/250 [==============================] - 0s 439us/step - loss: 62732.3945 - mae: 62732.3945 - val_loss: 61457.4375 - val_mae: 61457.4375
Epoch 49/100
250/250 [==============================] - 0s 438us/step - loss: 61656.2852 - mae: 61656.2852 - val_loss: 60464.4766 - val_mae: 60464.4766
Epoch 50/100
250/250 [==============================] - 0s 438us/step - loss: 60614.6211 - mae: 60614.6211 - val_loss: 59515.2383 - val_mae: 59515.2383
Epoch 51/100
250/250 [==============================] - 0s 441us/step - loss: 59620.8320 - mae: 59620.8320 - val_loss: 58617.8711 - val_mae: 58617.8711
Epoch 52/100
250/250 [==============================] - 0s 436us/step - loss: 58683.7617 - mae: 58683.7617 - val_loss: 57765.5156 - val_mae: 57765.5156
Epoch 53/100
250/250 [==============================] - 0s 435us/step - loss: 57796.4688 - mae: 57796.4688 - val_loss: 56941.6328 - val_mae: 56941.6328
Epoch 54/100
250/250 [==============================] - 0s 438us/step - loss: 56947.8789 - mae: 56947.8789 - val_loss: 56164.2109 - val_mae: 56164.2109
Epoch 55/100
250/250 [==============================] - 0s 499us/step - loss: 56154.0195 - mae: 56154.0195 - val_loss: 55462.4141 - val_mae: 55462.4141
Epoch 56/100
250/250 [==============================] - 0s 437us/step - loss: 55423.4102 - mae: 55423.4102 - val_loss: 54792.1133 - val_mae: 54792.1133
Epoch 57/100
250/250 [==============================] - 0s 437us/step - loss: 54746.5547 - mae: 54746.5547 - val_loss: 54178.2422 - val_mae: 54178.2422
Epoch 58/100
250/250 [==============================] - 0s 437us/step - loss: 54136.9336 - mae: 54136.9336 - val_loss: 53638.5312 - val_mae: 53638.5312
Epoch 59/100
250/250 [==============================] - 0s 440us/step - loss: 53589.6289 - mae: 53589.6289 - val_loss: 53157.3477 - val_mae: 53157.3477
Epoch 60/100
250/250 [==============================] - 0s 439us/step - loss: 53090.6523 - mae: 53090.6523 - val_loss: 52730.3945 - val_mae: 52730.3945
Epoch 61/100
250/250 [==============================] - 0s 437us/step - loss: 52642.8750 - mae: 52642.8750 - val_loss: 52342.9766 - val_mae: 52342.9766
Epoch 62/100
250/250 [==============================] - 0s 437us/step - loss: 52239.2773 - mae: 52239.2773 - val_loss: 52006.6484 - val_mae: 52006.6484
Epoch 63/100
250/250 [==============================] - 0s 439us/step - loss: 51889.8750 - mae: 51889.8750 - val_loss: 51727.5703 - val_mae: 51727.5703
Epoch 64/100
250/250 [==============================] - 0s 438us/step - loss: 51585.6523 - mae: 51585.6523 - val_loss: 51488.7070 - val_mae: 51488.7070
Epoch 65/100
250/250 [==============================] - 0s 436us/step - loss: 51327.1016 - mae: 51327.1016 - val_loss: 51301.6250 - val_mae: 51301.6250
Epoch 66/100
250/250 [==============================] - 0s 437us/step - loss: 51104.1836 - mae: 51104.1836 - val_loss: 51153.3711 - val_mae: 51153.3711
Epoch 67/100
250/250 [==============================] - 0s 439us/step - loss: 50915.8867 - mae: 50915.8867 - val_loss: 51028.8359 - val_mae: 51028.8359
Epoch 68/100
250/250 [==============================] - 0s 440us/step - loss: 50762.6797 - mae: 50762.6797 - val_loss: 50921.8555 - val_mae: 50921.8555
Epoch 69/100
250/250 [==============================] - 0s 439us/step - loss: 50632.1445 - mae: 50632.1445 - val_loss: 50842.5000 - val_mae: 50842.5000
Epoch 70/100
250/250 [==============================] - 0s 440us/step - loss: 50526.1875 - mae: 50526.1875 - val_loss: 50779.9141 - val_mae: 50779.9141
Epoch 71/100
250/250 [==============================] - 0s 438us/step - loss: 50442.6211 - mae: 50442.6211 - val_loss: 50731.0000 - val_mae: 50731.0000
Epoch 72/100
250/250 [==============================] - 0s 438us/step - loss: 50376.3086 - mae: 50376.3086 - val_loss: 50695.7734 - val_mae: 50695.7734
Epoch 73/100
250/250 [==============================] - 0s 439us/step - loss: 50321.9727 - mae: 50321.9727 - val_loss: 50669.1484 - val_mae: 50669.1484
Epoch 74/100
250/250 [==============================] - 0s 469us/step - loss: 50279.1055 - mae: 50279.1055 - val_loss: 50650.1250 - val_mae: 50650.1250
Epoch 75/100
250/250 [==============================] - 0s 440us/step - loss: 50244.4570 - mae: 50244.4570 - val_loss: 50636.0703 - val_mae: 50636.0703
Epoch 76/100
250/250 [==============================] - 0s 439us/step - loss: 50216.8945 - mae: 50216.8945 - val_loss: 50625.5703 - val_mae: 50625.5703
Epoch 77/100
250/250 [==============================] - 0s 440us/step - loss: 50193.5664 - mae: 50193.5664 - val_loss: 50616.8398 - val_mae: 50616.8398
Epoch 78/100
250/250 [==============================] - 0s 440us/step - loss: 50173.5898 - mae: 50173.5898 - val_loss: 50611.4766 - val_mae: 50611.4766
Epoch 79/100
250/250 [==============================] - 0s 476us/step - loss: 50155.1836 - mae: 50155.1836 - val_loss: 50604.5586 - val_mae: 50604.5586
Epoch 80/100
250/250 [==============================] - 0s 444us/step - loss: 50139.6172 - mae: 50139.6172 - val_loss: 50599.4922 - val_mae: 50599.4922
Epoch 81/100
250/250 [==============================] - 0s 439us/step - loss: 50125.0469 - mae: 50125.0469 - val_loss: 50594.6016 - val_mae: 50594.6016
Epoch 82/100
250/250 [==============================] - 0s 439us/step - loss: 50110.8594 - mae: 50110.8594 - val_loss: 50589.6211 - val_mae: 50589.6211
Epoch 83/100
250/250 [==============================] - 0s 445us/step - loss: 50098.3398 - mae: 50098.3398 - val_loss: 50582.8633 - val_mae: 50582.8633
Epoch 84/100
250/250 [==============================] - 0s 440us/step - loss: 50087.0195 - mae: 50087.0195 - val_loss: 50577.6328 - val_mae: 50577.6328
Epoch 85/100
250/250 [==============================] - 0s 443us/step - loss: 50075.7461 - mae: 50075.7461 - val_loss: 50571.2070 - val_mae: 50571.2070
Epoch 86/100
250/250 [==============================] - 0s 441us/step - loss: 50065.7109 - mae: 50065.7109 - val_loss: 50565.7461 - val_mae: 50565.7461
Epoch 87/100
250/250 [==============================] - 0s 440us/step - loss: 50055.2539 - mae: 50055.2539 - val_loss: 50558.8633 - val_mae: 50558.8633
Epoch 88/100
250/250 [==============================] - 0s 440us/step - loss: 50045.7812 - mae: 50045.7812 - val_loss: 50554.9609 - val_mae: 50554.9609
Epoch 89/100
250/250 [==============================] - 0s 440us/step - loss: 50037.0859 - mae: 50037.0859 - val_loss: 50547.5703 - val_mae: 50547.5703
Epoch 90/100
250/250 [==============================] - 0s 440us/step - loss: 50029.2773 - mae: 50029.2773 - val_loss: 50542.6758 - val_mae: 50542.6758
Epoch 91/100
250/250 [==============================] - 0s 441us/step - loss: 50021.2266 - mae: 50021.2266 - val_loss: 50537.8008 - val_mae: 50537.8008
Epoch 92/100
250/250 [==============================] - 0s 443us/step - loss: 50013.1914 - mae: 50013.1914 - val_loss: 50530.5859 - val_mae: 50530.5859
Epoch 93/100
250/250 [==============================] - 0s 440us/step - loss: 50004.9570 - mae: 50004.9570 - val_loss: 50525.6836 - val_mae: 50525.6836
Epoch 94/100
250/250 [==============================] - 0s 440us/step - loss: 49997.6953 - mae: 49997.6953 - val_loss: 50521.0000 - val_mae: 50521.0000
Epoch 95/100
250/250 [==============================] - 0s 441us/step - loss: 49990.8242 - mae: 49990.8242 - val_loss: 50515.2148 - val_mae: 50515.2148
Epoch 96/100
250/250 [==============================] - 0s 494us/step - loss: 49983.2266 - mae: 49983.2266 - val_loss: 50510.3086 - val_mae: 50510.3086
Epoch 97/100
250/250 [==============================] - 0s 445us/step - loss: 49977.3477 - mae: 49977.3477 - val_loss: 50504.5781 - val_mae: 50504.5781
Epoch 98/100
250/250 [==============================] - 0s 441us/step - loss: 49971.0117 - mae: 49971.0117 - val_loss: 50500.7383 - val_mae: 50500.7383
Epoch 99/100
250/250 [==============================] - 0s 441us/step - loss: 49964.1992 - mae: 49964.1992 - val_loss: 50495.3789 - val_mae: 50495.3789
Epoch 100/100
250/250 [==============================] - 0s 441us/step - loss: 49958.1602 - mae: 49958.1602 - val_loss: 50492.1992 - val_mae: 50492.1992

In [17]:
%load_ext tensorboard

In [19]:
%tensorboard --logdir regressionlogs/fit/20260326-214050

Reusing TensorBoard on port 6007 (pid 52740), started 0:00:04 ago. (Use '!kill 52740' to kill it.)

In [20]:
## Evaluate model on the test data
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 [==============================] - 0s 281us/step - loss: 50492.1992 - mae: 50492.1992
Test MAE : 50492.19921875

In [21]:
model.save('regression_model.h5')

/Users/pranav/Documents/AI projects/Churn Modelling/annclassification/venv/lib/python3.9/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(